export const SITE = {
  name: 'IsDigitle',
  domain: 'isdigitle.com',
  tagline: 'Where Digital Excellence Converges',
  description: 'IsDigitle is a premium digital services platform uniting elite agencies and specialists under one powerful umbrella — delivering SEO, development, design, Amazon, and marketing at the highest level.',
  email: 'hello@isdigitle.com',
  phone: '+92 300 0000000',
  whatsapp: '+923000000000',
  address: 'Rawalpindi, Pakistan',
  social: {
    linkedin: 'https://linkedin.com/company/isdigitle',
    twitter: 'https://twitter.com/isdigitle',
    instagram: 'https://instagram.com/isdigitle',
    facebook: 'https://facebook.com/isdigitle',
  },
  calendly: 'https://calendly.com/isdigitle',
}

export const SERVICES = [
  {
    id: 'seo',
    title: 'Search Engine Optimization',
    shortTitle: 'SEO',
    slug: '/services/seo',
    icon: 'TrendingUp',
    color: '#6C63FF',
    description: 'Dominate search rankings with our data-driven SEO frameworks. We engineer organic growth through technical precision, authority building, and content intelligence.',
    features: ['Technical SEO Audits', 'Keyword Strategy', 'Link Building', 'Local SEO', 'Content Optimization', 'Core Web Vitals'],
  },
  {
    id: 'web-dev',
    title: 'Website Development',
    shortTitle: 'Web Dev',
    slug: '/services/web-development',
    icon: 'Code2',
    color: '#00D4FF',
    description: 'High-performance websites engineered for speed, conversion, and scale. From Next.js to custom CMS — we architect digital experiences that convert.',
    features: ['Next.js / React', 'WordPress', 'Shopify', 'Custom E-commerce', 'API Integration', 'Performance Optimization'],
  },
  {
    id: 'web-design',
    title: 'Web Design',
    shortTitle: 'Design',
    slug: '/services/web-design',
    icon: 'Layers',
    color: '#F4C542',
    description: 'UI/UX design that stops the scroll. We craft premium digital identities that communicate authority, build trust, and drive measurable results.',
    features: ['UI/UX Strategy', 'Brand Identity', 'Figma Prototyping', 'Design Systems', 'Motion Design', 'Conversion Design'],
  },
  {
    id: 'amazon',
    title: 'Amazon Services',
    shortTitle: 'Amazon',
    slug: '/services/amazon',
    icon: 'ShoppingBag',
    color: '#FF9900',
    description: 'Full-cycle Amazon growth from product hunting to scaled PPC. We\'ve launched hundreds of private label brands with proven frameworks.',
    features: ['Private Label Launch', 'Amazon PPC', 'Product Research', 'Listing Optimization', 'Brand Registry', 'A+ Content'],
  },
  {
    id: 'digital-marketing',
    title: 'Digital Marketing',
    shortTitle: 'Marketing',
    slug: '/services/digital-marketing',
    icon: 'Megaphone',
    color: '#FF6B6B',
    description: 'Full-funnel digital marketing that fills pipelines. Google Ads, Meta, social media, and AI-powered automation working in unified precision.',
    features: ['Google Ads', 'Meta Ads', 'Social Media', 'Funnel Building', 'Lead Generation', 'AI Automation'],
  },
  {
    id: 'content',
    title: 'Content Marketing',
    shortTitle: 'Content',
    slug: '/services/digital-marketing',
    icon: 'FileText',
    color: '#4CAF50',
    description: 'Strategic content that builds authority and drives pipeline. Blog, video, email, and social content engineered to convert and rank.',
    features: ['Blog & Articles', 'Video Scripts', 'Email Sequences', 'Social Content', 'Thought Leadership', 'Content Strategy'],
  },
]

export const STATS = [
  { label: 'Projects Delivered', value: 850, suffix: '+' },
  { label: 'Revenue Generated', value: 42, suffix: 'M+', prefix: '$' },
  { label: 'Expert Partners', value: 60, suffix: '+' },
  { label: 'Client Retention', value: 96, suffix: '%' },
]

export const TESTIMONIALS = [
  {
    name: 'Sarah Mitchell',
    role: 'CEO',
    company: 'Nexus Retail Co.',
    avatar: 'SM',
    rating: 5,
    text: 'IsDigitle transformed our digital presence completely. Our organic traffic grew 340% in 6 months. Their SEO team knows exactly what Google wants — and they deliver it.',
  },
  {
    name: 'Ahmed Al-Rashid',
    role: 'Founder',
    company: 'Desert Bloom Brands',
    avatar: 'AA',
    rating: 5,
    text: 'From Amazon launch to $2M in year one. The team\'s product research was spot-on, PPC was optimized to perfection. Best investment we\'ve ever made.',
  },
  {
    name: 'Jessica Park',
    role: 'Head of Growth',
    company: 'TechPulse SaaS',
    avatar: 'JP',
    rating: 5,
    text: 'The website they built is converting at 4.2% — double our industry average. The design, the copy, the user flow — every detail was considered and executed beautifully.',
  },
  {
    name: 'Marcus Weber',
    role: 'E-commerce Director',
    company: 'Luxe Living EU',
    avatar: 'MW',
    rating: 5,
    text: 'Their Meta Ads team generated 680% ROAS in Q4. The creative strategy, the targeting, the optimization — it\'s a completely different level from other agencies we\'ve used.',
  },
  {
    name: 'Priya Sharma',
    role: 'CMO',
    company: 'HealthFirst India',
    avatar: 'PS',
    rating: 5,
    text: 'Local SEO dominance in 8 cities within 4 months. We went from invisible to #1 positions across all target markets. The ROI speaks for itself.',
  },
  {
    name: 'Daniel Okonkwo',
    role: 'Managing Director',
    company: 'AfriTech Solutions',
    avatar: 'DO',
    rating: 5,
    text: 'The AI automation systems IsDigitle built saved us 40+ hours per week. Lead generation is fully automated and qualified leads doubled. Genuinely world-class work.',
  },
]

export const PORTFOLIO = [
  {
    title: 'NovaSkin — E-commerce Revolution',
    category: 'Web Development + SEO',
    description: 'Complete digital overhaul for premium skincare brand. Shopify rebuild, SEO strategy, and paid media launch.',
    results: ['340% organic traffic growth', '$1.8M first-year revenue', '4.2% conversion rate'],
    tags: ['Shopify', 'SEO', 'Google Ads'],
    color: '#6C63FF',
    image: 'https://picsum.photos/800/600?random=1',
  },
  {
    title: 'UrbanNest — Amazon Domination',
    category: 'Amazon Private Label',
    description: 'End-to-end Amazon private label launch for home decor brand. Product research, launch strategy, and PPC management.',
    results: ['$2.1M revenue in year one', '#1 BSR in category', '4.7★ average rating'],
    tags: ['Amazon PPC', 'Private Label', 'Brand Registry'],
    color: '#FF9900',
    image: 'https://picsum.photos/800/600?random=2',
  },
  {
    title: 'Fortis Capital — Authority Design',
    category: 'Brand Identity + Web Design',
    description: 'Premium brand identity and website for boutique investment firm. Full design system and conversion-focused UX.',
    results: ['Rebrand launched in 3 weeks', '60% increase in qualified leads', 'Awwwards Honorable Mention'],
    tags: ['UI/UX', 'Branding', 'Figma'],
    color: '#F4C542',
    image: 'https://picsum.photos/800/600?random=3',
  },
  {
    title: 'PulseHealth — 8-City Local SEO',
    category: 'Local SEO + Content',
    description: 'Multi-location local SEO strategy for healthcare network across 8 major cities. GBP optimization, citations, and content.',
    results: ['#1 rankings in all 8 cities', '280% appointment bookings', '90-day ranking timeline'],
    tags: ['Local SEO', 'Content', 'GBP'],
    color: '#4CAF50',
    image: 'https://picsum.photos/800/600?random=4',
  },
  {
    title: 'MetroLeads — Funnel Architecture',
    category: 'Funnel Building + Meta Ads',
    description: 'Full-funnel lead generation system for real estate developer. Meta Ads, landing pages, CRM automation.',
    results: ['680% ROAS on Meta', '1,200+ qualified leads/month', '38% lower CPL'],
    tags: ['Meta Ads', 'Funnel', 'CRM'],
    color: '#FF6B6B',
    image: 'https://picsum.photos/800/600?random=5',
  },
  {
    title: 'ClearPath SaaS — Growth Engine',
    category: 'SEO + Content Marketing',
    description: 'B2B SaaS content and SEO strategy. Pillar content, thought leadership, and technical SEO overhaul.',
    results: ['520% organic growth in 8mo', '400+ ranking keywords', '$340K pipeline from SEO'],
    tags: ['SaaS SEO', 'Content', 'Technical SEO'],
    color: '#00D4FF',
    image: 'https://picsum.photos/800/600?random=6',
  },
]

export const PRICING_PLANS = [
  {
    name: 'Growth',
    price: 1500,
    period: 'month',
    description: 'For businesses ready to establish a serious digital presence.',
    color: '#6C63FF',
    features: [
      'SEO Fundamentals (10 keywords)',
      'Website Audit & Optimization',
      'Google My Business Setup',
      'Monthly SEO Report',
      '2x Blog Posts / Month',
      'Basic Google Ads Management',
      'Email Support',
    ],
    cta: 'Start Growing',
    popular: false,
  },
  {
    name: 'Scale',
    price: 3500,
    period: 'month',
    description: 'For ambitious brands ready to dominate their market.',
    color: '#00D4FF',
    features: [
      'Advanced SEO (30+ keywords)',
      'Full Technical SEO',
      'Link Building (10 links/mo)',
      'Google + Meta Ads Management',
      'Landing Page Design',
      '6x Blog Posts / Month',
      'Monthly Strategy Call',
      'WhatsApp Priority Support',
      'CRO Audits',
    ],
    cta: 'Start Scaling',
    popular: true,
  },
  {
    name: 'Dominate',
    price: 7500,
    period: 'month',
    description: 'Total digital dominance. For market leaders who refuse second place.',
    color: '#F4C542',
    features: [
      'Full-Stack Digital Marketing',
      'Enterprise SEO (100+ keywords)',
      'Aggressive Link Building (25/mo)',
      'All Ad Platforms Managed',
      'Funnel Design & Build',
      'AI Lead Gen Automation',
      '16x Content Pieces / Month',
      'Dedicated Account Manager',
      'Weekly Strategy Sessions',
      'Competitor Monitoring',
      'Custom Reporting Dashboard',
    ],
    cta: 'Dominate Now',
    popular: false,
  },
]

export const PROCESS_STEPS = [
  {
    step: '01',
    title: 'Discovery Call',
    description: 'We audit your current digital position, understand your goals, and identify the highest-leverage opportunities specific to your market.',
    duration: '60 min',
  },
  {
    step: '02',
    title: 'Strategy Architecture',
    description: 'Our expert network crafts a bespoke digital strategy. No templates, no copy-paste playbooks — a precise growth plan built for your specific situation.',
    duration: '3–5 days',
  },
  {
    step: '03',
    title: 'Team Assembly',
    description: 'We assign the exact specialists your project demands from our network of 60+ vetted experts. The right people, not the available people.',
    duration: '1–2 days',
  },
  {
    step: '04',
    title: 'Execution',
    description: 'Disciplined execution against the strategy. Transparent progress tracking, weekly updates, and real-time dashboard access at every stage.',
    duration: 'Ongoing',
  },
  {
    step: '05',
    title: 'Optimization',
    description: 'Continuous data analysis and optimization cycles. We double down on what works, cut what doesn\'t, and stay ahead of market shifts.',
    duration: 'Monthly',
  },
  {
    step: '06',
    title: 'Scale',
    description: 'As results compound, we expand the strategy. Your digital presence becomes a self-reinforcing growth engine that widens the gap with competitors.',
    duration: 'Quarterly',
  },
]

export const FAQS = [
  {
    question: 'How does the partner network model work?',
    answer: 'IsDigitle brings together 60+ vetted specialist agencies and experts under one coordinated platform. When you work with us, you get access to specialized talent for every discipline — SEO, development, Amazon, advertising — without managing multiple vendor relationships. One account manager. One strategy. Multiple experts.',
  },
  {
    question: 'How long until I see results?',
    answer: 'It depends on the service. Paid media (Google/Meta Ads) typically shows results within 2–4 weeks. SEO is a longer game — you\'ll see measurable movement in 60–90 days, with significant results at 4–6 months. Website and design projects typically deliver within 3–6 weeks. We set clear timelines and expectations from day one.',
  },
  {
    question: 'Do you work with businesses outside Pakistan?',
    answer: 'Absolutely. We work with clients across the US, UK, UAE, Europe, and Australia. Our team operates across time zones, and our processes are designed for seamless remote collaboration. Many of our highest-performing client relationships are international.',
  },
  {
    question: 'What makes you different from other digital agencies?',
    answer: 'Three things: (1) The partner network model gives you specialist-grade expertise in every discipline rather than generalists handling everything. (2) We\'re conversion-obsessed — every strategy is built around measurable business outcomes, not vanity metrics. (3) Radical transparency — you get full access to data, strategy, and progress at all times.',
  },
  {
    question: 'Can I start with just one service?',
    answer: 'Yes. Many clients start with a single high-priority service and expand as results come in. We\'ll recommend the service with the highest leverage for your specific situation during the discovery call.',
  },
  {
    question: 'What\'s included in the free consultation?',
    answer: 'A 60-minute strategy session where we audit your current digital presence, identify your biggest growth opportunities, and outline a custom strategy. You\'ll leave with actionable insights regardless of whether you decide to work with us. No pitch decks, no hard sells.',
  },
]
